apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "owe.uiName" . }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.ui.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
