{{- if .Values.postgres.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.usernameSecret.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.postgres.auth.usernameSecret.key }}: {{ required "postgres.auth.secretValues.username is required when postgres.auth.createSecret=true" .Values.postgres.auth.secretValues.username | quote }}
  {{ .Values.postgres.auth.passwordSecret.key }}: {{ required "postgres.auth.secretValues.password is required when postgres.auth.createSecret=true" .Values.postgres.auth.secretValues.password | quote }}
{{- end }}
