apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "owe-staging.serviceName" . }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.service.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
